<#
    Qualifire -- build 3, step 1 of 2: PREPARE

    Everything that changes the project before spending a cloud build:
    sanity checks, the two native packages, the preview app id, and the icon
    check. Nothing here talks to Expo's servers.

        cd "C:\Users\natha\Claude personal projects\Qualifire\scripts"
        .\build3-prepare.ps1            # do it
        .\build3-prepare.ps1 -DryRun    # just say what it would do

    Safe to run twice -- every step checks before it changes anything, and the
    files it edits are backed up next to themselves as *.bak.
#>
[CmdletBinding()]
param(
    [switch]$DryRun,
    [switch]$SkipTests
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$app  = Join-Path $repo 'app'

function Say  ($m) { Write-Host "  $m" }
function Step ($m) { Write-Host "`n$m" -ForegroundColor Cyan }
function Ok   ($m) { Write-Host "  OK  $m" -ForegroundColor Green }
function Warn ($m) { Write-Host "  !!  $m" -ForegroundColor Yellow }
function Would($m) { Write-Host "  (dry run) would $m" -ForegroundColor DarkGray }

# PowerShell with $ErrorActionPreference='Stop' treats ANYTHING a native command
# writes to stderr as a terminating error -- node's harmless
# MODULE_TYPELESS_PACKAGE_JSON warning was enough to kill the run. So native
# calls go through here: stderr is captured as text, and only the EXIT CODE
# decides success.
function Invoke-Native {
    param([scriptblock]$Cmd)
    $prev = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        $out  = & $Cmd 2>&1 | ForEach-Object { "$_" }
        $code = $LASTEXITCODE
    } finally { $ErrorActionPreference = $prev }
    [pscustomobject]@{ Output = $out; Code = $code }
}

function Backup ($path) {
    if (-not $DryRun -and (Test-Path $path)) { Copy-Item $path "$path.bak" -Force }
}

if (-not (Test-Path $app)) { throw "app folder not found at $app" }
Push-Location $app
try {
    Write-Host "Qualifire build 3 -- prepare" -ForegroundColor White
    Say "repo: $repo"
    if ($DryRun) { Warn 'DRY RUN -- nothing will be changed' }

    # ---------------------------------------------------------------- 1. tools
    Step '1. Toolchain'
    $node = (node --version)
    Say "node $node"
    if ([int](($node -replace '^v(\d+)\..*$', '$1')) -lt 22) {
        throw "node 22+ required (the test runner uses --experimental-strip-types); found $node"
    }
    Ok 'node version fine'

    # ------------------------------------------------------------- 2. preflight
    Step '2. Preflight -- typecheck and tests'
    if ($SkipTests) {
        Warn 'skipped by -SkipTests'
    } else {
        Say 'npx tsc --noEmit'
        $r = Invoke-Native { npx tsc --noEmit }
        if ($r.Code -ne 0) {
            $r.Output | ForEach-Object { Say $_ }
            throw 'TypeScript errors -- fix before building'
        }
        Ok 'tsc clean'

        Say 'node --experimental-strip-types tests/run.ts'
        $r = Invoke-Native { node --experimental-strip-types tests/run.ts }
        $summary = $r.Output | Select-String -Pattern '^\d+ tests:' | Select-Object -Last 1
        if ($r.Code -ne 0) {
            $r.Output | Select-String -Pattern '^FAIL' | ForEach-Object { Warn $_ }
            throw 'test failures -- fix before building'
        }
        Ok $summary
    }

    # ------------------------------------------------------- 3. native packages
    Step '3. Native packages (the whole D-026 slate -- MapLibre is out by decision)'
    $pkg = Get-Content package.json -Raw | ConvertFrom-Json
    $want = @('expo-audio', 'react-native-safe-area-context')
    $deps = $pkg.dependencies.PSObject.Properties.Name
    $missing = @($want | Where-Object { $deps -notcontains $_ })
    if ($missing.Count -eq 0) {
        Ok 'both already installed'
    } elseif ($DryRun) {
        Would "npx expo install $($missing -join ' ')"
    } else {
        Say "npx expo install $($missing -join ' ')"
        $r = Invoke-Native { npx expo install @missing }
        $r.Output | ForEach-Object { Say $_ }
        if ($r.Code -ne 0) { throw 'expo install failed' }
        Ok 'installed'
    }

    # ------------------------------------------------- 4. preview app id (D-026)
    Step '4. Preview variant gets its own app id, so it installs ALONGSIDE the dev client'
    $cfg = Join-Path $app 'app.config.js'
    if (Test-Path $cfg) {
        Ok 'app.config.js already present -- leaving it alone'
    } elseif ($DryRun) {
        Would 'write app.config.js (preview => com.nathanbonher.qualifire.preview)'
    } else {
        @'
// Generated by scripts/build3-prepare.ps1 (D-026).
// The preview profile builds a SEPARATE app so it sits next to the dev client
// instead of replacing it. Everything else comes from app.json unchanged.
module.exports = ({ config }) => {
  if (process.env.APP_VARIANT !== 'preview') return config;
  return {
    ...config,
    name: 'Qualifire Preview',
    android: { ...config.android, package: `${config.android.package}.preview` },
  };
};
'@ | Set-Content -Path $cfg -Encoding UTF8
        Ok 'wrote app.config.js'
    }

    # eas.json: the preview profile must set APP_VARIANT for the above to fire
    $easPath = Join-Path $app 'eas.json'
    $eas = Get-Content $easPath -Raw | ConvertFrom-Json
    $preview = $eas.build.preview
    $hasEnv = ($preview.PSObject.Properties.Name -contains 'env') -and ($preview.env.APP_VARIANT -eq 'preview')
    if ($hasEnv) {
        Ok 'eas.json preview profile already sets APP_VARIANT'
    } elseif ($DryRun) {
        Would 'add env.APP_VARIANT=preview to eas.json build.preview'
    } else {
        Backup $easPath
        if ($preview.PSObject.Properties.Name -contains 'env') {
            $preview.env | Add-Member -NotePropertyName APP_VARIANT -NotePropertyValue 'preview' -Force
        } else {
            $preview | Add-Member -NotePropertyName env -NotePropertyValue ([pscustomobject]@{ APP_VARIANT = 'preview' })
        }
        $eas | ConvertTo-Json -Depth 20 | Set-Content -Path $easPath -Encoding UTF8
        Ok 'patched eas.json (backup: eas.json.bak)'
    }

    # ------------------------------------------------------------- 5. app icon
    Step '5. Launcher icon'
    $icon = Join-Path $app 'assets\icon.png'
    if (Test-Path $icon) {
        Ok 'assets\icon.png present'
    } else {
        Warn 'assets\icon.png MISSING -- the build still succeeds, with the default Expo icon.'
        Say  'Drop a 1024x1024 PNG there (white lap ring + yellow gate slash) and rerun to fix.'
    }

    # ------------------------------------------------------- 6. route assets
    Step '6. Route map assets (the faked map -- no native module)'
    $routes = Join-Path $app 'assets\routes\routes.json'
    if (Test-Path $routes) {
        $n = @((Get-Content $routes -Raw | ConvertFrom-Json).routes.PSObject.Properties).Count
        Ok "$n pre-rendered routes bundled"
    } else {
        Warn 'assets\routes\routes.json missing -- regenerate with:'
        Say  'python data\analysis\08_build_route_assets.py   (run from the repo root)'
    }

    Step 'Ready.'
    Say 'Next:  .\build3-build.ps1'
}
finally { Pop-Location }
