// Generated by scripts/build3-prepare.ps1 (D-026).
// The preview profile builds a SEPARATE app so it sits next to the dev client
// instead of replacing it. Everything else comes from app.json unchanged.
module.exports = ({ config }) => {
  if (process.env.APP_VARIANT !== 'preview') return config;
  return {
    ...config,
    name: 'Qualifire Preview',
    android: { ...config.android, package: `${config.android.package}.preview` },
  };
};
