#!/usr/bin/env python3
"""Render the cycle-025 DRAFT chrome palettes to design/drafts/.

Does NOT touch make_screens.py and does NOT write design/canonical/ or design/edited/.
Each draft is rendered as a day-mode screen (the builders' only theme-name branches --
make_screens.py lines 598 and 869 -- must see "day") with THEMES["day"] temporarily
swapped for the draft's tokens and restored immediately afterwards.

Output: design/drafts/<screen>_draft-<palette>.svg  (9 screens x 3 palettes = 27)
"""
from __future__ import annotations

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import make_screens as ms
from draft_palettes import DRAFT_THEMES, INHERITED_FROM_DAY

README = """# design/drafts/ -- DRAFT palette mockups, NOT canonical

These SVGs are an exploration for Nathan to look at. They are **not** ship-ready, they are
**not** what the app renders, and no app code refers to them. The canonical mockups -- the
ones that mirror what actually ships -- remain the 18 files in `design/canonical/`.

Generated by `design/make_draft_screens.py` from the token sets in
`design/draft_palettes.py`. Regenerate with:

    cd design && python3 make_draft_screens.py

Three chrome palettes: **pink**, **lightblue**, **green**. Each is rendered as a day-mode
screen, so the Settings screen's Appearance control shows "day" selected in all three --
that is correct, not a bug.

A theme here recolours **chrome only** -- backgrounds, cards, borders, text, buttons, the
route line. The scoring **verdict** colours (purple career-best, green, yellow, the no-data
grey, the rider dot, the map casing) are the app's vocabulary and render identically in
every palette. `accentText` is inherited unchanged from the day theme because the neutral
verdict tier is drawn with it.

`CONTRAST.md` in this folder carries the computed WCAG contrast ratios for every pair, from
`design/check_draft_contrast.py`. Nothing here was eyeballed.
"""


def main() -> int:
    repo_root = os.path.normpath(os.path.join(HERE, ".."))
    out_dir = os.path.join(HERE, "drafts")
    base_allowed = ms.load_allowed_colors(repo_root)
    original_day = dict(ms.THEMES["day"])

    # Guard rails: key parity with the real theme dict, and the verdict-inherited tokens.
    for name, tok in DRAFT_THEMES.items():
        if set(tok) != set(original_day):
            print(f"FATAL: palette {name} key set differs from THEMES['day']", file=sys.stderr)
            return 2
        for k in INHERITED_FROM_DAY:
            if tok[k] != original_day[k]:
                print(f"FATAL: palette {name} overrides inherited verdict token {k!r} "
                      f"({tok[k]} != {original_day[k]})", file=sys.stderr)
                return 2

    all_errors: list[str] = []
    to_write: list[tuple[str, str]] = []
    for name, tok in DRAFT_THEMES.items():
        allowed = set(base_allowed) | {ms._normalize_hex(v) for v in tok.values()}
        ms.THEMES["day"] = dict(tok)
        try:
            for screen in ms.IMPLEMENTED:
                svg_root = ms.BUILDERS[screen]("day", repo_root)
                fname = f"{screen}_draft-{name}.svg"
                errs = ms.validate(svg_root, fname, allowed)
                if errs:
                    all_errors.extend(errs)
                    continue
                to_write.append((fname, ms.serialize(svg_root)))
        finally:
            ms.THEMES["day"] = dict(original_day)

    if all_errors:
        print("VALIDATION FAILED:", file=sys.stderr)
        for e in all_errors:
            print("  " + e, file=sys.stderr)
        return 1

    os.makedirs(out_dir, exist_ok=True)
    for fname, content in to_write:
        with open(os.path.join(out_dir, fname), "w", encoding="utf-8") as f:
            f.write(content)
    with open(os.path.join(out_dir, "README.md"), "w", encoding="utf-8") as f:
        f.write(README)

    print(f"Wrote {len(to_write)} draft SVGs + README.md to {out_dir}")
    for fname in sorted(f for f, _ in to_write):
        print("  " + fname)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
