"""One-shot data fix (cycle 025): EveningA's drawn map line.

routes.json's EveningA entry was built by 08_build_route_assets.py's pick()
("most recent A-variant ride" = 20260813-1618-work2home-19726172105.gpx),
whose first ~700 m took a different street: up to 218 m off the
parity-anchored EveningA reference the engine times against, and 183 m off
the START gate. The live map drew that line (RECORD armed preview + running
map) while sector timing — which reads tests/fixtures/refs.json, never this
file — stayed correct (Nathan, 2026-08-27). Rebuilds ONLY EveningA's `path`,
`gateIdx`, `sourceRide` from the PARITY.md medoid ride, with script 08's
exact decimation (stride-2 GPX parse, every 3rd point, 5-dp rounding) and
nearest-vertex gate indexing. Gates, the Web-Mercator transform and
EveningA.png are untouched (the PNG fallback rung keeps its baked — still
stale — line; flagged in the cycle record). demos/routes-data.js (3-route
preview mirror) receives the identical entry.

Run: python3 data/analysis/11_rebuild_eveninga_asset_path.py   (idempotent)
"""
import json, os, re

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
J = lambda *p: os.path.join(ROOT, *p)

# PARITY_REFS.EveningA in app/tests/build_fixtures.ts — keep in sync.
MEDOID = '20260724-1838-work2home-19448004625.gpx'

txt = open(J('data', 'activities', MEDOID), encoding='utf-8').read()
pts = [(float(a), float(b))
       for a, b in re.findall(r'<trkpt lat="([-\d.]+)" lon="([-\d.]+)"', txt)][::2]
path = [[round(a, 5), round(b, 5)] for a, b in pts[::3]]

def nearest_idx(poly, lat, lon):  # same maths as 08_build_route_assets.py
    best, bi = 1e18, 0
    for i, (a, b) in enumerate(poly):
        d = (a - lat) ** 2 + (b - lon) ** 2
        if d < best:
            best, bi = d, i
    return bi

def patch(routes):
    e = routes['EveningA']
    e['path'] = path
    e['gateIdx'] = [nearest_idx(path, g['lat'], g['lon']) for g in e['gates']]
    e['sourceRide'] = MEDOID + ' (parity medoid; map-line fix 2026-08-27)'
    return e['gateIdx']

jp = J('app', 'assets', 'routes', 'routes.json')
bundle = json.load(open(jp, encoding='utf-8'))
gate_idx = patch(bundle['routes'])
with open(jp, 'w', encoding='utf-8') as f:
    json.dump(bundle, f, indent=1)
    f.write('\n')

HEAD = ('// GENERATED by data/analysis/08_build_route_assets.py — do not edit.\n'
        'window.ROUTES_JSON = ')
dp = J('demos', 'routes-data.js')
js = open(dp, encoding='utf-8').read()
assert js.startswith(HEAD), 'routes-data.js header changed — stop, report'
mirror = json.loads(js[len(HEAD):].rstrip().rstrip(';'))
patch(mirror['routes'])
with open(dp, 'w', encoding='utf-8') as f:
    f.write(HEAD)
    json.dump(mirror, f, indent=1)
    f.write(';\n')

print(f'EveningA rebuilt from {MEDOID}: {len(path)} path points, gateIdx {gate_idx}')
